[features]
seeds = false
skip-lint = false

[programs.localnet]
whistle_pool = "8A6rYQ7Kf7aqg8JkU7z6W83wCZvmohND7wiXPBhkpowx"
whistle_merkle = "GSCeQ9qUybayPEUULjBu7Gk8p89g97FkoGgTeUE11tmk"
whistle_verifier = "C6cKqUzwMdL5Tm9vNsYNjPwZjprthyypywmgne3RkSD4"

[programs.devnet]
whistle_pool = "8A6rYQ7Kf7aqg8JkU7z6W83wCZvmohND7wiXPBhkpowx"
whistle_merkle = "GSCeQ9qUybayPEUULjBu7Gk8p89g97FkoGgTeUE11tmk"
whistle_verifier = "C6cKqUzwMdL5Tm9vNsYNjPwZjprthyypywmgne3RkSD4"

[programs.mainnet]
whistle_pool = "8A6rYQ7Kf7aqg8JkU7z6W83wCZvmohND7wiXPBhkpowx"
whistle_merkle = "GSCeQ9qUybayPEUULjBu7Gk8p89g97FkoGgTeUE11tmk"
whistle_verifier = "C6cKqUzwMdL5Tm9vNsYNjPwZjprthyypywmgne3RkSD4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../keys/deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
